### ISSUE TITLE
comments should be completed

### ISSUE THREAD

**Issue by qizidog** [jiawei92/OSM2GMNS#2]
我查看了源代码，发现几乎没有注解用来描述类和方法的功能，作为一个开源项目，这应该被完善。
I checked the source code and found that there were few comments to describe the functions of classes and methods, which should be supplied as an open source project.

**Comment by jiawei92** [comment]
We will try to add comments for each function and class in the next release

**Comment by jiawei92** [comment]
> 我查看了源代码，发现几乎没有注解用来描述类和方法的功能，作为一个开源项目，这应该被完善。
> I checked the source code and found that there were few comments to describe the functions of classes and methods, which should be supplied as an open source project.

We will try to add comments for each function and class in the next release
